<a href="https://colab.research.google.com/github/Willen-CesarCosta/projeto1-willen-dev/blob/master/Projeto_Automa%C3%A7%C3%A3o_analises_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Automação de Sistemas e Processos com Python

### Desafio:

Todos os dias, o nosso sistema atualiza as vendas do dia anterior.
O seu trabalho diário, como analista, é enviar um e-mail para a diretoria, assim que começar a trabalhar, com o faturamento e a quantidade de produtos vendidos no dia anterior

E-mail da diretoria: seugmail+diretoria@gmail.com<br>
Local onde o sistema disponibiliza as vendas do dia anterior: https://drive.google.com/drive/folders/149xknr9JvrlEnhNWO49zPcw0PW5icxga?usp=sharing

Para resolver isso, vamos usar o pyautogui, uma biblioteca de automação de comandos do mouse e do teclado

In [ ]:
#lógica de programação
# passo 1:pecorrer todos os arquivos da pasta base de dados(vendas)
#passo 2: importar base de vendas
#passo 3: compilar dados de dados
#passo 4: calcular quantidade do produto mais vendido
#passo 5: calcular o produto que mais faturou
#passo 6: calcular loja/cidade que mais vendeu - criar grafico/dashboard

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import os
import pandas as pd

lista_arquivo = os.listdir("/content/drive/MyDrive/Curso Básico de Python/Vendas")
display(lista_arquivo)

tabela_total = pd.DataFrame()

# Passo 2 - Importar as bases de dados de vendas
for arquivo in lista_arquivo:
  # se tem "Vendas" no nome do arquivo, então
  if "Vendas" in arquivo:
    # importar o arquivo
    tabela = pd.read_csv(f"/content/drive/MyDrive/Curso Básico de Python/Vendas/{arquivo}")
    tabela_total = tabela_total.append(tabela)

# Passo 3 - Tratar / Compilar as bases de dados
display(tabela_total)

# Passo 4 - Calcular o produto mais vendido (em quantidade)
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida"]].sort_values(by="Quantidade Vendida", ascending=False)
display(tabela_produtos)

# Passo 5 - Calcular o produto que mais faturou (em faturamento)
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']

tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento", ascending=False)
display(tabela_faturamento)

# Passo 6 - Calcular a loja/cidade que mais vendeu (em faturamento) - criar um gráfico/dashboard
tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']]
display(tabela_lojas)

import plotly.express as px

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()

['Vendas - Fortaleza.csv',
 'Vendas - Goiás.csv',
 'Vendas - São Paulo.csv',
 'Vendas - Belo Horizonte.csv',
 'Devolucoes - Rio de Janeiro.csv',
 'Devolucoes - Salvador.csv',
 'Devolucoes - Fortaleza.csv',
 'Devolucoes - Goiás.csv',
 'Vendas - Salvador.csv',
 'Vendas - Rio de Janeiro.csv',
 'Devolucoes - São Paulo.csv',
 'Devolucoes - Porto Alegre.csv',
 'Devolucoes - Belo Horizonte.csv',
 'Vendas - Recife.csv',
 'Vendas - Porto Alegre.csv',
 'Vendas - Curitiba.csv',
 'Devolucoes - Recife.csv',
 'Devolucoes - Curitiba.csv']

,Unnamed: 0,SKU,Produto,Quantidade Vendida,Primeiro Nome,Sobrenome,Data,Loja,Preco Unitario,Unnamed: 8
0,2,HL1148,Câmera,2,Camila,Sobral,10/21/2018,Fortaleza,2100,NaN
1,3,HL1918,iPhone,3,Clara,Bruno,7/8/2018,Fortaleza,5300,NaN
2,4,HL9962,Android,4,Eduardo,Pacheco,12/19/2018,Fortaleza,3400,NaN
3,11,HL1918,iPhone,2,Rafael,Rocha,12/22/2018,Fortaleza,5300,NaN
4,15,HL2714,Tablet,2,Caio,Ferreira,7/26/2018,Fortaleza,1600,NaN
...,...,...,...,...,...,...,...,...,...,...
714,9859,HL2714,Tablet,1,Júlio,Fraga,12/25/2018,Curitiba,1600,NaN
715,9876,HL4379,Televisão,5,Bruno,Mota,4/30/2018,Curitiba,2500,NaN
716,9918,HL1148,Câmera,2,Lucas,Reis,12/27/2018,Curitiba,2100,NaN
717,9944,HL1918,iPhone,5,Raphael,Kurtz,7/16/2018,Curitiba,5300,NaN
718,9998,HL7348,SmartWatch,1,Vinícius,Antunes,12/10/2018,Curitiba,1400,NaN

            Quantidade Vendida
Produto
iPhone                    8974
Televisão                 5931
Notebook                  3249
Android                   3183
SmartWatch                2980
Tablet                    2921
Câmera                    2805

            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000

                Faturamento
Loja
Belo Horizonte      6480300
Curitiba            7060500
Fortaleza          14087900
Goiás               7441800
Porto Alegre        6868600
Recife              7303000
Rio de Janeiro     14867800
Salvador           13111300
São Paulo          22098300

### Vamos agora ler o arquivo baixado para pegar os indicadores

- Faturamento
- Quantidade de Produtos

### Vamos agora enviar um e-mail pelo gmail

#### Use esse código para descobrir qual a posição de um item que queira clicar

- Lembre-se: a posição na sua tela é diferente da posição na minha tela